name 'duosecurity-duo_unix'
version '0.3.1'
source 'git://github.com/duosecurity/puppet-duo_unix'
author 'Duo Security'
license 'GPLv2'
summary 'duo_unix Puppet Module'
description 'duo_unix Puppet Module'
project_page 'https://github.com/duosecurity/puppet-duo_unix'
